//! NSPasteboard change watcher: the shell edge of clipboard history.
//!
//! An NSTimer polls the general pasteboard's changeCount every 0.5 s (the
//! pasteboard has no notification API; polling the counter is how every
//! clipboard manager does it). On a new count the plain-text contents are
//! read and recorded into a `beckon_core::clipstore::ClipStore`, which is
//! persisted to `<store_root>/clipboard.json` after every accepted entry.
//! The store file is written through `persist::write_atomic`, which
//! creates it with mode 0600, and the store root itself is 0700, so
//! clipboard history is owner-readable only.
//!
//! Privacy rules, non-negotiable:
//!
//! 1. A change whose type list carries any of the standard pasteboard
//!    privacy markers is skipped entirely: password managers and other
//!    secret-handling apps mark their writes with
//!    "org.nspasteboard.TransientType", "org.nspasteboard.ConcealedType",
//!    or "org.nspasteboard.AutoGeneratedType" (see nspasteboard.org).
//!    The check goes through [[pasteboard types] containsObject:].
//! 2. Strings larger than [`MAX_TEXT_BYTES`] (100 KB) are skipped: nobody
//!    scrolls a launcher panel for a megabyte of text, and the store file
//!    stays small.
//! 3. beckon's own pasteboard writes are never recorded. Every write path
//!    in this process must call [`note_own_write`] immediately after
//!    writing (activate() here does; the engine's calc-copy path does via
//!    the integrator), which tells the watcher to ignore that changeCount.
//!
//! Threading invariants: like the rest of the shell, everything here is
//! main-thread only in the running app. [`start`] attaches its timer to
//! the calling thread's run loop; the engine calls it on the main thread
//! during init, so the timer lives on the main run loop (in the common
//! modes, so it keeps ticking while the panel is up). The WATCHER Mutex
//! exists to satisfy Rust's static-safety rules, not to enable
//! cross-thread use, and is never held across an FFI call.

// The integrator wires start/items/activate/note_own_write into the

use crate::ffi::{self, msg, Bool, Id, Sel};
use beckon_core::clipstore::{ClipEntry, ClipStore};
use beckon_core::persist;
use beckon_core::router::{Item, ItemKind};
use std::mem::transmute;
use std::path::{Path, PathBuf};
use std::sync::{Mutex, OnceLock};
use std::time::{SystemTime, UNIX_EPOCH};

/// Poll interval for the changeCount timer, in seconds. Half a second is
/// the customary clipboard-manager cadence: imperceptible to the user,
/// negligible cost (one integer read per tick when nothing changed).
const POLL_INTERVAL_SECONDS: f64 = 0.5;

/// Privacy rule 2: skip strings larger than this many bytes (100 KB).
const MAX_TEXT_BYTES: usize = 100 * 1024;

/// Privacy rule 1: pasteboard marker types that mean "do not record".
/// These are the de facto standard published at nspasteboard.org and
/// honored by password managers.
const MARKER_TYPES: [&str; 3] = [
    "org.nspasteboard.TransientType",
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.AutoGeneratedType",
];

/// The pasteboard type read and written here (the literal value of
/// NSPasteboardTypeString; no headers are linked to import the constant).
const PASTEBOARD_TYPE_STRING: &str = "public.utf8-plain-text";

/// The clipboard history file, under the beckon store root.
const CLIPBOARD_FILE: &str = "clipboard.json";

/// Rows [`items`] returns at most: the same single-keystroke panel depth
/// the engine uses for app results.
const MAX_ITEMS: usize = 9;

/// Title budget in characters, ellipsis included.
const TITLE_MAX_CHARS: usize = 60;

struct Watcher {
    store: ClipStore,
    /// Where the store persists; saved after every accepted entry.
    path: PathBuf,
    /// The changeCount already handled (or deliberately ignored). A tick
    /// that reads this exact value does nothing.
    last_change_count: isize,
}

static WATCHER: OnceLock<Mutex<Watcher>> = OnceLock::new();

fn watcher() -> Option<&'static Mutex<Watcher>> {
    WATCHER.get()
}

/// Current wall clock as unix seconds; a clock before the epoch degrades
/// to 0 rather than panicking. (Same policy as the engine's clock read.)
fn now_secs() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0)
}

/// Load the persisted history. Missing file is a fresh install; a corrupt
/// file must not take the launcher down, so it logs to stderr and starts
/// fresh (the next save overwrites it).
fn load_store(path: &Path) -> ClipStore {
    match ClipStore::load(path) {
        Ok(Some(store)) => store,
        Ok(None) => ClipStore::new(),
        Err(e) => {
            eprintln!(
                "beckon: corrupt clipboard store {}: {e}; starting fresh",
                path.display()
            );
            ClipStore::new()
        }
    }
}

/// Begin watching the general pasteboard. Idempotent: the second and
/// later calls return immediately. Loads the persisted store, snapshots
/// the current changeCount (whatever is on the pasteboard at startup is
/// not captured; only changes from here on are), and schedules the poll
/// timer on the calling thread's run loop. The engine calls this once on
/// the main thread, so in the app the timer lives on the main run loop.
pub fn start() {
    if WATCHER.get().is_some() {
        return;
    }
    let root = match persist::ensure_store_root() {
        Ok(root) => root,
        Err(e) => {
            let fallback = persist::store_root();
            eprintln!(
                "beckon: cannot create store root {}: {e}; clipboard history may not persist",
                fallback.display()
            );
            fallback
        }
    };
    let path = root.join(CLIPBOARD_FILE);
    let store = load_store(&path);
    // Safety: changeCount has encoding q@: (returns NSInteger, no args).
    let last_change_count = unsafe {
        let pb = general_pasteboard();
        msg!(isize: pb, ffi::sel("changeCount"))
    };
    if WATCHER
        .set(Mutex::new(Watcher {
            store,
            path,
            last_change_count,
        }))
        .is_err()
    {
        // Lost a set race; the winner's timer is already scheduled.
        return;
    }
    // Safety: called once (guarded by the OnceLock above), so the class
    // name is not yet registered; the tick Imp matches its v@:@ encoding.
    unsafe { schedule_timer() };
}

/// Record that beckon itself just wrote to the general pasteboard, so the
/// watcher ignores that change (privacy rule 3). Must be called right
/// after the write, before the next poll tick can observe it. A no-op
/// before [`start`].
pub fn note_own_write() {
    let Some(w) = watcher() else {
        return;
    };
    // Safety: as in start(); changeCount returns NSInteger.
    let count = unsafe {
        let pb = general_pasteboard();
        msg!(isize: pb, ffi::sel("changeCount"))
    };
    w.lock().unwrap().last_change_count = count;
}

/// Clipboard history as registry items, for the panel. An empty query
/// returns the most recent entries (pinned first, then newest first, the
/// store's display order); a non-empty query is a case-insensitive
/// substring search via [`ClipStore::search`]. Both are capped at
/// [`MAX_ITEMS`]. Empty before [`start`].
pub fn items(query: &str) -> Vec<Item> {
    let Some(w) = watcher() else {
        return Vec::new();
    };
    let guard = w.lock().unwrap();
    items_from(&guard.store, query, now_secs())
}

/// Copy the entry behind `id` (shape "clip.<entry id>") back to the
/// general pasteboard and bump it to the top of history. Calls
/// [`note_own_write`] so the watcher does not re-record the copy. Paste
/// injection into the frontmost app is a later bead; this only writes the
/// pasteboard.
pub fn activate(id: &str) -> Result<(), String> {
    let entry_id = parse_clip_id(id).ok_or_else(|| format!("not a clipboard item id: {id}"))?;
    let w = watcher().ok_or_else(|| "clipboard watcher not started".to_string())?;
    let text = w
        .lock()
        .unwrap()
        .store
        .get(entry_id)
        .map(|e| e.text.clone())
        .ok_or_else(|| format!("unknown clipboard entry {entry_id}"))?;
    if !copy_to_pasteboard(&text) {
        return Err("pasteboard write failed".to_string());
    }
    note_own_write();
    // Re-add with the current time so the entry rises to the top; a save
    // failure loses persistence, not the copy, so it only warns.
    let mut guard = w.lock().unwrap();
    guard.store.add(&text, now_secs());
    if let Err(e) = guard.store.save(&guard.path) {
        eprintln!(
            "beckon: cannot save clipboard store {}: {e}",
            guard.path.display()
        );
    }
    Ok(())
}

/// Shape rows for the panel out of a store snapshot. Pure given `now`;
/// unit tested directly with injected clocks.
fn items_from(store: &ClipStore, query: &str, now: u64) -> Vec<Item> {
    store
        .search(query)
        .into_iter()
        .take(MAX_ITEMS)
        .map(|e| {
            Item::new(
                &format!("clip.{}", e.id),
                &title_of(&e.text),
                &subtitle_of(e, now),
                ItemKind::ClipboardEntry,
            )
        })
        .collect()
}

/// Extract the numeric entry id from an item id of shape "clip.<n>".
fn parse_clip_id(id: &str) -> Option<u64> {
    id.strip_prefix("clip.")?.parse().ok()
}

/// First line of the text, truncated to [`TITLE_MAX_CHARS`] characters
/// with a trailing ellipsis when it does not fit.
fn title_of(text: &str) -> String {
    let first = text.lines().next().unwrap_or("");
    if first.chars().count() <= TITLE_MAX_CHARS {
        first.to_string()
    } else {
        let head: String = first.chars().take(TITLE_MAX_CHARS - 1).collect();
        format!("{head}…")
    }
}

/// "pinned · 3m ago" or "3m ago": a relative age plus the pin marker.
/// Deterministic given `now`; a future `last_copied` reads as "just now".
fn subtitle_of(entry: &ClipEntry, now: u64) -> String {
    let age = age_label(now.saturating_sub(entry.last_copied));
    if entry.pinned {
        format!("pinned · {age}")
    } else {
        age
    }
}

/// Coarse relative age. Coarse on purpose: the panel refreshes per
/// keystroke, not per second, so minute granularity is plenty.
fn age_label(elapsed_secs: u64) -> String {
    if elapsed_secs < 60 {
        "just now".to_string()
    } else if elapsed_secs < 3600 {
        format!("{}m ago", elapsed_secs / 60)
    } else if elapsed_secs < 86400 {
        format!("{}h ago", elapsed_secs / 3600)
    } else {
        format!("{}d ago", elapsed_secs / 86400)
    }
}

/// Privacy rules 2 and 3 of the capture path as one pure predicate:
/// record only non-empty text within the size cap that is not marked
/// private. (The marker flag is computed at the FFI edge.)
fn should_store(text: &str, has_marker: bool) -> bool {
    !has_marker && !text.is_empty() && text.len() <= MAX_TEXT_BYTES
}

/// One poll tick: read the changeCount, and on a new value capture the
/// string contents subject to the privacy rules. The changeCount is
/// always advanced first so a skipped change is skipped forever, not
/// retried every tick.
fn poll() {
    let Some(w) = watcher() else {
        return;
    };
    // Timer callbacks between run loop pool drains can pile up the
    // autoreleased NSStrings created below; scope a pool to the tick.
    let _pool = ffi::AutoreleasePool::new();
    // Safety: changeCount returns NSInteger; types returns an NSArray or
    // nil; containsObject: takes an object and returns BOOL;
    // stringForType: takes an NSString and returns an NSString or nil
    // (both accepted by nsstring_to_string).
    let text = unsafe {
        let pb = general_pasteboard();
        let count = msg!(isize: pb, ffi::sel("changeCount"));
        {
            let mut guard = w.lock().unwrap();
            if count == guard.last_change_count {
                return;
            }
            guard.last_change_count = count;
        }
        let has_marker = has_marker_type(pb);
        let ns = msg!(Id: pb, ffi::sel("stringForType:"),
            Id: ffi::nsstring(PASTEBOARD_TYPE_STRING));
        let text = ffi::nsstring_to_string(ns);
        if !should_store(&text, has_marker) {
            return;
        }
        text
    };
    let mut guard = w.lock().unwrap();
    guard.store.add(&text, now_secs());
    if let Err(e) = guard.store.save(&guard.path) {
        eprintln!(
            "beckon: cannot save clipboard store {}: {e}",
            guard.path.display()
        );
    }
}

/// The general pasteboard singleton.
///
/// # Safety
/// Caller is on the thread discipline documented in the module header.
unsafe fn general_pasteboard() -> Id {
    msg!(Id: ffi::class("NSPasteboard"), ffi::sel("generalPasteboard"))
}

/// Privacy rule 1: does the current pasteboard change carry any of the
/// [`MARKER_TYPES`]?
///
/// # Safety
/// `pb` must be a valid NSPasteboard.
unsafe fn has_marker_type(pb: Id) -> bool {
    let types = msg!(Id: pb, ffi::sel("types"));
    if types.is_null() {
        return false;
    }
    MARKER_TYPES.iter().any(|marker| {
        msg!(Bool: types, ffi::sel("containsObject:"), Id: ffi::nsstring(marker)) != 0
    })
}

/// Write `text` to the general pasteboard as plain text. Mirrors the
/// engine's calc-copy write; callers that should not be re-captured must
/// follow up with [`note_own_write`].
fn copy_to_pasteboard(text: &str) -> bool {
    // Safety: clearContents returns NSInteger (the new change count) and
    // setString:forType: takes two NSStrings and returns BOOL.
    unsafe {
        let pb = general_pasteboard();
        let _ = msg!(isize: pb, ffi::sel("clearContents"));
        msg!(Bool: pb, ffi::sel("setString:forType:"),
            Id: ffi::nsstring(text),
            Id: ffi::nsstring(PASTEBOARD_TYPE_STRING))
            != 0
    }
}

/// The timer callback: encoding v@:@ (self, _cmd, the NSTimer).
extern "C" fn timer_tick(_this: Id, _sel: Sel, _timer: Id) {
    poll();
}

/// Define the timer-target class, instantiate it, and schedule the
/// repeating poll timer on the current thread's run loop in the common
/// modes (so it keeps ticking during panel tracking). The timer and its
/// target intentionally live for the whole process (ffi invariant 3).
///
/// # Safety
/// Call once per process (the class name must not already be registered),
/// from the thread whose run loop should host the timer.
unsafe fn schedule_timer() {
    let cls = ffi::define_class(
        "BeckonPasteboardTimerTarget",
        "NSObject",
        &[(
            "beckonPasteboardTick:",
            transmute::<extern "C" fn(Id, Sel, Id), ffi::Imp>(timer_tick),
            "v@:@",
        )],
    );
    let target = msg!(Id: msg!(Id: cls, ffi::sel("alloc")), ffi::sel("init"));
    // timerWithTimeInterval:target:selector:userInfo:repeats: returns an
    // autoreleased timer; scheduling it retains it, and the timer retains
    // its target, so both survive the pool.
    let timer = msg!(Id: ffi::class("NSTimer"),
        ffi::sel("timerWithTimeInterval:target:selector:userInfo:repeats:"),
        f64: POLL_INTERVAL_SECONDS,
        Id: target,
        Sel: ffi::sel("beckonPasteboardTick:"),
        Id: ffi::NIL,
        Bool: ffi::YES);
    let run_loop = msg!(Id: ffi::class("NSRunLoop"), ffi::sel("currentRunLoop"));
    // The literal value of NSRunLoopCommonModes.
    msg!((): run_loop, ffi::sel("addTimer:forMode:"),
        Id: timer, Id: ffi::nsstring("kCFRunLoopCommonModes"));
}

#[cfg(test)]
mod tests {
    use super::*;

    fn entry(id: u64, text: &str, last_copied: u64, pinned: bool) -> ClipEntry {
        ClipEntry {
            id,
            hash: beckon_core::clipstore::fnv1a64(text.as_bytes()),
            text: text.to_string(),
            first_copied: last_copied,
            last_copied,
            copy_count: 1,
            pinned,
        }
    }

    #[test]
    fn marker_types_are_the_published_uti_set() {
        assert!(MARKER_TYPES.contains(&"org.nspasteboard.TransientType"));
        assert!(MARKER_TYPES.contains(&"org.nspasteboard.ConcealedType"));
        assert!(MARKER_TYPES.contains(&"org.nspasteboard.AutoGeneratedType"));
        assert_eq!(MARKER_TYPES.len(), 3);
    }

    #[test]
    fn should_store_rejects_marked_empty_and_oversized() {
        assert!(should_store("hello", false));
        // Privacy rule 1: a marker skips the change no matter the text.
        assert!(!should_store("hello", true));
        // Non-string or stringless changes read back as empty.
        assert!(!should_store("", false));
        // Privacy rule 2: the cap is inclusive; one byte over is out.
        let at_cap = "x".repeat(MAX_TEXT_BYTES);
        assert!(should_store(&at_cap, false));
        let over_cap = "x".repeat(MAX_TEXT_BYTES + 1);
        assert!(!should_store(&over_cap, false));
    }

    #[test]
    fn title_is_first_line_truncated_with_ellipsis() {
        assert_eq!(title_of("short"), "short");
        assert_eq!(title_of("line one\nline two"), "line one");
        assert_eq!(title_of(""), "");
        // Exactly at the budget: untouched.
        let exact = "e".repeat(TITLE_MAX_CHARS);
        assert_eq!(title_of(&exact), exact);
        // One over: 59 chars plus the ellipsis, 60 total.
        let over = "o".repeat(TITLE_MAX_CHARS + 1);
        let title = title_of(&over);
        assert_eq!(title.chars().count(), TITLE_MAX_CHARS);
        assert!(title.ends_with('…'));
        assert!(title.starts_with(&"o".repeat(TITLE_MAX_CHARS - 1)));
        // Truncation counts characters, not bytes.
        let unicode = "ü".repeat(TITLE_MAX_CHARS + 5);
        assert_eq!(title_of(&unicode).chars().count(), TITLE_MAX_CHARS);
    }

    #[test]
    fn subtitle_age_labels_are_coarse_and_deterministic() {
        assert_eq!(age_label(0), "just now");
        assert_eq!(age_label(59), "just now");
        assert_eq!(age_label(60), "1m ago");
        assert_eq!(age_label(3599), "59m ago");
        assert_eq!(age_label(3600), "1h ago");
        assert_eq!(age_label(86399), "23h ago");
        assert_eq!(age_label(86400), "1d ago");
        assert_eq!(age_label(10 * 86400), "10d ago");
    }

    #[test]
    fn subtitle_marks_pins_and_tolerates_future_timestamps() {
        let plain = entry(1, "text", 1000, false);
        assert_eq!(subtitle_of(&plain, 1000 + 120), "2m ago");
        let pinned = entry(2, "text", 1000, true);
        assert_eq!(subtitle_of(&pinned, 1000 + 120), "pinned · 2m ago");
        // A clock that moved backward reads as "just now", never panics.
        assert_eq!(subtitle_of(&plain, 500), "just now");
    }

    #[test]
    fn parse_clip_id_accepts_only_the_clip_shape() {
        assert_eq!(parse_clip_id("clip.7"), Some(7));
        assert_eq!(parse_clip_id("clip.0"), Some(0));
        assert_eq!(parse_clip_id("clip."), None);
        assert_eq!(parse_clip_id("clip.x"), None);
        assert_eq!(parse_clip_id("clip.-1"), None);
        assert_eq!(parse_clip_id("app.safari"), None);
        assert_eq!(parse_clip_id("7"), None);
    }

    #[test]
    fn items_from_shapes_ids_titles_and_subtitles() {
        let mut store = ClipStore::new();
        let a = store.add("alpha text", 100);
        let b = store.add("beta line one\nbeta line two", 200);
        let items = items_from(&store, "", 260);
        assert_eq!(items.len(), 2);
        // Newest first on the empty query.
        assert_eq!(items[0].id, format!("clip.{b}"));
        assert_eq!(items[0].title, "beta line one");
        assert_eq!(items[0].subtitle, "1m ago");
        assert_eq!(items[0].kind, ItemKind::ClipboardEntry);
        assert_eq!(items[1].id, format!("clip.{a}"));
        assert_eq!(items[1].title, "alpha text");
        assert_eq!(items[1].subtitle, "2m ago");
    }

    #[test]
    fn items_from_empty_query_caps_at_nine_recent() {
        let mut store = ClipStore::new();
        for i in 0..12u64 {
            store.add(&format!("entry {i}"), 100 + i);
        }
        let items = items_from(&store, "", 200);
        assert_eq!(items.len(), MAX_ITEMS);
        // The most recent (highest timestamp) leads.
        assert_eq!(items[0].title, "entry 11");
        assert_eq!(items[8].title, "entry 3");
    }

    #[test]
    fn items_from_searches_and_puts_pins_first() {
        let mut store = ClipStore::new();
        let pinned = store.add("needle old", 10);
        store.add("hay", 20);
        let fresh = store.add("fresh needle", 30);
        store.pin(pinned);
        let items = items_from(&store, "needle", 100);
        assert_eq!(items.len(), 2);
        assert_eq!(items[0].id, format!("clip.{pinned}"));
        assert!(items[0].subtitle.starts_with("pinned · "));
        assert_eq!(items[1].id, format!("clip.{fresh}"));
        assert!(items_from(&store, "zzz", 100).is_empty());
    }

    /// Read the general pasteboard's plain-text contents ("" for none).
    ///
    /// # Safety
    /// Hardware-test only; see the module threading notes.
    unsafe fn read_pasteboard_string() -> String {
        let pb = general_pasteboard();
        let ns = msg!(Id: pb, ffi::sel("stringForType:"),
            Id: ffi::nsstring(PASTEBOARD_TYPE_STRING));
        ffi::nsstring_to_string(ns)
    }

    /// Run the current thread's run loop for `seconds`, firing any timers
    /// scheduled on it (the default mode is one of the common modes).
    ///
    /// # Safety
    /// runUntilDate: takes an NSDate; dateWithTimeIntervalSinceNow:
    /// returns an autoreleased NSDate.
    unsafe fn pump_run_loop(seconds: f64) {
        let run_loop = msg!(Id: ffi::class("NSRunLoop"), ffi::sel("currentRunLoop"));
        let date = msg!(Id: ffi::class("NSDate"),
            ffi::sel("dateWithTimeIntervalSinceNow:"), f64: seconds);
        msg!((): run_loop, ffi::sel("runUntilDate:"), Id: date);
    }

    /// What the hardware body observed, asserted only after the owner's
    /// pasteboard has been restored.
    struct HardwareObservations {
        wrote: bool,
        captured_title: Option<String>,
        copy_count_after_capture: Option<u64>,
        store_file_mode: u32,
        activate_result: Result<(), String>,
        pasteboard_after_activate: String,
        copy_count_after_second_pump: Option<u64>,
    }

    fn copy_count_of(unique: &str) -> Option<u64> {
        let guard = watcher().expect("watcher started").lock().unwrap();
        guard.store.search(unique).first().map(|e| e.copy_count)
    }

    fn hardware_body(unique: &str) -> HardwareObservations {
        start();
        // A second start must be a no-op, not a double class definition.
        start();
        // Write like a foreign app would: no note_own_write, so the
        // watcher must capture it on the next tick.
        let wrote = copy_to_pasteboard(unique);
        // Safety: helpers above; the poll interval is 0.5 s, so 1.2 s of
        // pumping guarantees at least one tick.
        unsafe { pump_run_loop(1.2) };
        let captured_title = items("")
            .first()
            .map(|i| i.title.clone())
            .filter(|t| t == &title_of(unique));
        let copy_count_after_capture = copy_count_of(unique);
        let store_file_mode = {
            use std::os::unix::fs::PermissionsExt as _;
            let guard = watcher().expect("watcher started").lock().unwrap();
            std::fs::metadata(&guard.path)
                .map(|m| m.permissions().mode() & 0o777)
                .unwrap_or(0)
        };
        let entry_id = {
            let guard = watcher().expect("watcher started").lock().unwrap();
            guard.store.search(unique).first().map(|e| e.id)
        };
        let activate_result = match entry_id {
            Some(id) => activate(&format!("clip.{id}")),
            None => Err("entry never captured".to_string()),
        };
        // Safety: as above.
        let pasteboard_after_activate = unsafe { read_pasteboard_string() };
        // The activate write bumped the changeCount; note_own_write must
        // keep the watcher from re-recording it as a fresh copy.
        unsafe { pump_run_loop(1.2) };
        let copy_count_after_second_pump = copy_count_of(unique);
        HardwareObservations {
            wrote,
            captured_title,
            copy_count_after_capture,
            store_file_mode,
            activate_result,
            pasteboard_after_activate,
            copy_count_after_second_pump,
        }
    }

    /// The live-pasteboard round trip. Ignored by default because it
    /// touches the machine's real clipboard; run it alone with
    /// `cargo test -p beckon-macos -- --ignored hardware`. The owner's
    /// clipboard string is saved first and restored exactly, asserted
    /// last thing, and the store lands under a temp BECKON_HOME that is
    /// deleted afterward.
    #[test]
    #[ignore = "drives the live pasteboard; run manually with --ignored"]
    fn hardware_pasteboard_round_trip() {
        let _pool = ffi::AutoreleasePool::new();
        let dir = std::env::temp_dir().join(format!("beckon-pasteboard-hw-{}", std::process::id()));
        std::fs::create_dir_all(&dir).expect("create temp BECKON_HOME");
        std::env::set_var("BECKON_HOME", &dir);
        // Safety: read helper above.
        let original = unsafe { read_pasteboard_string() };
        let unique = format!(
            "beckon pasteboard hardware test {} {}",
            std::process::id(),
            now_secs()
        );
        // Everything that mutates the pasteboard runs under catch_unwind
        // so the restore below happens even if an assertion-shaped step
        // panics mid-flight.
        let outcome =
            std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| hardware_body(&unique)));
        // Restore the owner's clipboard exactly, no matter what happened.
        if original.is_empty() {
            // Safety: clearContents returns NSInteger.
            unsafe {
                let pb = general_pasteboard();
                let _ = msg!(isize: pb, ffi::sel("clearContents"));
            }
        } else {
            assert!(copy_to_pasteboard(&original), "restore write failed");
        }
        note_own_write();
        // Safety: read helper above.
        let restored = unsafe { read_pasteboard_string() };
        std::env::remove_var("BECKON_HOME");
        let _ = std::fs::remove_dir_all(&dir);
        // Proof of restoration by length and content hash; the owner's
        // clipboard text itself is never printed.
        println!(
            "hardware: original len={} fnv={:016x}; restored len={} fnv={:016x}",
            original.len(),
            beckon_core::clipstore::fnv1a64(original.as_bytes()),
            restored.len(),
            beckon_core::clipstore::fnv1a64(restored.as_bytes()),
        );
        assert_eq!(
            restored, original,
            "the owner's clipboard must be exactly as it was found"
        );
        let obs = match outcome {
            Ok(obs) => obs,
            Err(panic) => std::panic::resume_unwind(panic),
        };
        assert!(obs.wrote, "test write to the pasteboard failed");
        assert_eq!(
            obs.captured_title,
            Some(title_of(&unique)),
            "watcher must capture the test string within one tick"
        );
        assert_eq!(obs.copy_count_after_capture, Some(1));
        assert_eq!(obs.store_file_mode, 0o600, "clipboard.json must be 0600");
        assert_eq!(obs.activate_result, Ok(()));
        assert_eq!(
            obs.pasteboard_after_activate, unique,
            "activate must copy the full text back"
        );
        // 1 from capture + 1 from the activate bump; note_own_write kept
        // the watcher from adding a third.
        assert_eq!(obs.copy_count_after_second_pump, Some(2));
    }
}
